### PR TITLE
Reports

### PR DESCRIPTION
**Pull request by princemusonerwa**
Adding Printing functionality on both users and properties

### CODE REVIEW

**Review by eliekayitare — APPROVED** [review]
Print

**Review by ngirimana — COMMENTED** [review]
remove localhost from proxy and assign real IP

**Review by ngirimana — DISMISSED** [review]
remove local host

**Review by eliekayitare — APPROVED** [review]
print

**Review by eliekayitare — APPROVED** [review]
print

**Review by VenantTumukunde — APPROVED** [review]
cool.

**Pull request merged**
